[package]
name = "enum-traits-proc-macros"
version = "0.1.0"
authors = ["carado <carado@carado.moe>"]
edition = "2018"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
syn = { version = "1.0", features = ["derive"] }
quote = "1.0.9"
proc-macro2 = "1.0.26"
num-bigint = "0.4.0"

